export const metadata = {
  title: 'Sri-chat',
  description: 'Generated by Next.js',
}
import SideBar from '@/components/SideBar'
import '@/styles/globals.css'
import { SessionProvider } from '../components/SessionProvider'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/pages/api/auth/[...nextauth]'
import Login from '../components/Login'
import ClientProvider from '../components/ClientProvider'

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions)
  console.log(session)
  return (
    <html >
      <head/>
      <body>
        <SessionProvider session={session}>
          {!session ? (
                <Login/>
            ) : (
            <div className='flex'>
            {/*side bar */}
              <div className='bg-[#202123] max-w-xs h-screen overflow-y-auto md:min-w-[20rem]'>
              <SideBar/>
              </div>
              
  
            {/*client provider-notification*/}
            <ClientProvider />
  
            <div className='bg-[#343541] flex-1'>{children}</div>
          
          </div>
          )}
     
        </SessionProvider>
        </body>
    </html>
  )
}
